CREATE OR REPLACE TRIGGER EJ3
AFTER INSERT OR DELETE ON VENTAS
FOR EACH ROW
BEGIN
IF INSERTING THEN
    UPDATE PRODUCTOS
    SET STOCK = STOCK - 1
    WHERE CODPRODUCTO = :old.codproducto;
ELSIF DELETING THEN
    UPDATE PRODUCTOS
    SET STOCK = STOCK + 1
    WHERE CODPRODUCTO = :old.codproducto;
END IF;
END;
/

CREATE OR REPLACE PROCEDURE EJ3
IS

vUno VARCHAR2(10);
suma NUMBER(10) := 0;

CURSOR uno IS SELECT LINEAPRODUCTO, NOMBRE FROM PRODUCTOS;

CURSOR dos IS SELECT CODPRODUCTO, STOCK, PRECIOUNITARIO FROM PRODUCTOS WHERE LINEAPRODUCTO = vUno;

BEGIN

SELECT SUM(PRECIOUNITARIO) INTO suma FROM PRODUCTOS;

FOR v_uno IN uno LOOP
    DBMS_OUTPUT.PUT_LINE(v_uno.LINEAPRODUCTO || ' ' || v_uno.NOMBRE);
    vUno := v_uno.LINEAPRODUCTO;
    FOR v_dos IN dos LOOP
        DBMS_OUTPUT.PUT_LINE('      ' || v_dos.CODPRODUCTO || ' ' || v_dos.STOCK || ' ' || v_dos.PRECIOUNITARIO);
    END LOOP;
END LOOP;

DBMS_OUTPUT.PUT_LINE('SUMA TOTAL: ' || suma);

END;
/

SET SERVEROUTPUT ON
BEGIN
EJ3();
END;
/

