CREATE TABLE FARMACIA(
numero NUMBER(5) CONSTRAINT PK_FARM PRIMARY KEY,
nombre VARCHAR2(50),
direccion VARCHAR2(50),
ciudad VARCHAR2(50)
);

CREATE TABLE FARMACEUTICO(
nif VARCHAR2(9) CONSTRAINT PK_FARM_NIF PRIMARY KEY,
nombre VARCHAR2(50),
fecha_nacimiento DATE,
fecha_titulo DATE,
ciudad VARCHAR2(50),
CONSTRAINT DIF_TIT CHECK(EXTRACT(YEAR FROM fecha_titulo) >= EXTRACT(YEAR FROM fecha_nacimiento) + 23)
);

CREATE TABLE LABORATORIO(
codigo VARCHAR2(10) CONSTRAINT PK_LAB PRIMARY KEY,
nombre VARCHAR2(50)
);

CREATE TABLE MEDICAMENTO(
codigo VARCHAR2(20) CONSTRAINT PK_MEDIC PRIMARY KEY,
nombre VARCHAR2(50),
precio NUMBER(10,2),
cantidad NUMBER(5), 
codigo_laboratorio VARCHAR2(10) CONSTRAINT FK_COD_LAB REFERENCES LABORATORIO(codigo)
);

CREATE TABLE TRABAJA_EN(
numero_farmacia NUMBER(5) CONSTRAINT FK_NUM_FARMA REFERENCES FARMACIA(numero),
nif VARCHAR2(9) CONSTRAINT FK_NIF_FARMACE REFERENCES FARMACEUTICO(nif),
fecha DATE DEFAULT SYSDATE,
salario NUMBER(6) CONSTRAINT SUELDO_MIN_MAX CHECK (salario BETWEEN 1200 AND 4500),
CONSTRAINT PK_CONJ PRIMARY KEY(numero_farmacia,nif)
);

CREATE TABLE ACCION(
codigo VARCHAR2(20) CONSTRAINT PK_ACCION PRIMARY KEY,
descripcion VARCHAR2(100) CONSTRAINT MAYUS CHECK(UPPER(descripcion) = descripcion)
);

CREATE TABLE SIRVE_PARA(
codigo_medicamento VARCHAR2(20) CONSTRAINT FK_COD_MED REFERENCES MEDICAMENTO(codigo),
tipo_accion VARCHAR2(20) CONSTRAINT FK_TIPO REFERENCES ACCION(codigo),
CONSTRAINT PK_CONJUNTO_SIRVE PRIMARY KEY(codigo_medicamento,tipo_accion)
);

--EJERCICIO.1

--NO SE PODRÍA PORQUE LA PRIMARY KEY EN LA TABLA "TRABAJA_EN" ES EL CONJUNTO DEL NIF DEL FARMACEUTICO Y DEL CODIGO DE FARMACIA,
--AL METERLOS EN OTRA FECHA DISTINTA, COMO ESTA ES LA ÚNICA QUE CAMBIA PERO NO ESTÁ EN EL CONJUNTO DE LAS PRIMARY KEY,
--NO NOS DEJARÍA INSERTARLO YA QUE LOS VALORES INTRODUCIDOS DE LAS PRIMARY KEY EL DIA X SERÍAN LOS MISMOS EL DIA Y,
--DEBERIAMOS AÑADIR AL CONJUNTO DE LAS PRIMARY KEY EL CAMPO FECHA, PARA QUE VARIE CADA DIA Y ASI NO LOS TOME COMO VALORES REPETIDOS.
--LO HACEMOS DEBAJO: ----------------------------------------------------------------------------------------------------

ALTER TABLE TRABAJA_EN
DROP CONSTRAINT PK_CONJ;

ALTER TABLE TRABAJA_EN
add CONSTRAINT PK_CONJ PRIMARY KEY (numero_farmacia,nif,fecha);

ALTER TABLE LABORATORIO
ADD cif VARCHAR2(8) CONSTRAINT CIF_LAB CHECK(REGEXP_LIKE(CIF, '^[A-Z]{2}[0-8]{6}$'));

ALTER TABLE FARMACEUTICO
DROP COLUMN CIUDAD;

ALTER TABLE LABORATORIO
modify nombre CONSTRAINT PRIMERA_MAYUS CHECK(initcap(nombre) = nombre);

INSERT INTO farmacia(numero, nombre, direccion, ciudad)
VALUES(12345, 'Farmacia de Sevilla', 'Av. Reyes Catolicos', 'Sevilla');

INSERT INTO FARMACEUTICO(nif, nombre)
VALUES('75432280p', 'Inma Olias');

INSERT INTO TRABAJA_EN(numero_farmacia, nif, fecha, salario)
VALUES(12345, '75432280p', '01-JAN-2018', 1200);

UPDATE TRABAJA_EN
SET salario = salario * 1.2
WHERE nif = '75432280p';

INSERT INTO medicamento(codigo, nombre)
VALUES('123456', 'CuraloTodo');

INSERT INTO medicamento(codigo, nombre)
VALUES('456789', 'CuraloTodoMejorQueElAnterior');

INSERT INTO ACCION(codigo, descripcion)
VALUES('123456', 'SOLO CURA LA MIGRAÑA');

INSERT INTO ACCION(codigo, descripcion)
VALUES('456789', 'ES MEJOR QUE EL ANTERIOR PERO SIRVE PARA LO MISMO, SOLO CURA LA MIGRAÑA');

ALTER TABLE TRABAJA_EN
DISABLE CONSTRAINT FK_NUM_FARMA;

DELETE FROM FARMACIA
WHERE ciudad = 'Sevilla';

UPDATE ACCION
SET descripcion = 'AHORA SOLO CURA LA CEFALEA'
WHERE codigo = '123456';

UPDATE ACCION
SET descripcion = 'AHORA ES MUCHO MEJOR QUE EL ANTERIOR PERO SIRVE PARA LO MISMO, SOLO CURA LA CEFALEA'
WHERE codigo = '456789';

DROP TABLE SIRVE_PARA;
DROP TABLE ACCION;
DROP TABLE TRABAJA_EN;
DROP TABLE MEDICAMENTO;
DROP TABLE LABORATORIO;
DROP TABLE FARMACEUTICO;
DROP TABLE FARMACIA;
