1. CREAR TABLAS: 

CREATE TABLE CABALLOS
(
CodCaballo VARCHAR2(4) CONSTRAINT PK_CODCABALLO PRIMARY KEY,
Nombre VARCHAR2(20) NOT NULL,
Peso NUMBER(3) CONSTRAINT peso CHECK (Peso IN(240,300)),
Fecha_nacimiento DATE CONSTRAINT NAC_CABALLO CHECK (EXTRACT(YEAR FROM Fecha_nacimiento)> 2000),
Propietario VARCHAR2 (25),
Nacionalidad VARCHAR2(20) CONSTRAINT NAC_MAYUS CHECK(regexp_like(UPPER(Nacionalidad),Nacionalidad))
);

CREATE TABLE CARRERAS
(
CodCarrera VARCHAR2(4) CONSTRAINT PK_CODCARRERA PRIMARY KEY,
Fecha_Hora DATE,
Importe_Premio NUMBER(6),
Apuesta_Limite NUMBER(5,2) CONSTRAINT APUEST_LIMIT CHECK(Apuesta_Limite < 20000)
);

CREATE TABLE PARTICIPACIONES 
(
CodCaballo VARCHAR2(4) CONSTRAINT FK_CODCABALLO REFERENCES CABALLOS(CodCaballo),
CodCarrera VARCHAR(4) CONSTRAINT FK_CODCARRERA REFERENCES CARRERAS(CodCarrera),
Dorsal NUMBER(2) NOT NULL,
Jockey VARCHAR2(10) NOT NULL,
Posicion_Final NUMBER(2) CONSTRAINT POSIC_POSITIVO CHECK(Posicion_Final > 0),
CONSTRAINT PK_CAB_CARR PRIMARY KEY (CodCaballo,CodCarrera)
);

CREATE TABLE CLIENTES
(
DNI VARCHAR2(10) CONSTRAINT FORMATO CHECK(REGEXP_LIKE(DNI,'^[0-9]{8}[A-Z]{1}$')),
Nombre VARCHAR2(20),
Nacionalidad VARCHAR2(20) CONSTRAINT NAC_MAYUS_CLI CHECK(regexp_like(UPPER(Nacionalidad),Nacionalidad)),
CONSTRAINT PK_DNI PRIMARY KEY(DNI)
);

CREATE TABLE APUESTAS 
(
DNICliente VARCHAR2(10) CONSTRAINT FK_DNICLI REFERENCES CLIENTES(DNI),
CodCaballo VARCHAR2(4) CONSTRAINT FK_CODCABALLO_APUESTAS REFERENCES CABALLOS(CodCaballo),
CodCarrera VARCHAR(4) CONSTRAINT FK_CODCARRERA_APUESTAS REFERENCES CARRERAS(CodCarrera),
Importe NUMBER(6) DEFAULT 300 NOT NULL,
Tantoporuno NUMBER(4,2) CONSTRAINT TANTO_MAYOR1 CHECK(Tantoporuno > 1),
CONSTRAINT PK_DNI_CARR_CAB PRIMARY KEY (DNICliente,CodCaballo,CodCarrera)
);

2.INSERTA EL REGISTRO NECESARIO PARA GUARDAR LA INFORMACION:

INSERT INTO clientes (DNI,Nacionalidad)
VALUES ('12345678A','ESCOCÉS');

INSERT INTO caballos(CodCaballo,Nombre,Peso)
VALUES ('CAB1','Rudolf',300);

INSERT INTO CARRERAS(CodCarrera,Fecha_Hora)
VALUES ('CAR1','05-JUL-2009');

INSERT INTO apuestas (DNICliente,CodCaballo,CodCarrera,Importe,Tantoporuno)
VALUES ('12345678A','CAB1','CAR1',2000,30);

3. INSCRIBE A 2 CABALLOS EN AL CARRERA CON CODIGO C6...

INSERT INTO CABALLOS(CodCaballo,Nombre)
VALUES ('CAB2','VayaPenaDeCaballaso');

INSERT INTO CABALLOS(CodCaballo,Nombre)
VALUES ('CAB3','ElMejorCaballote');

INSERT INTO CARRERAS (CodCarrera)
VALUES ('C6');

INSERT INTO PARTICIPACIONES (CodCaballo,CodCarrera,Dorsal,Jockey)
VALUES ('CAB2','C6',01,'Eustaquio');

INSERT INTO PARTICIPACIONES (CodCaballo,CodCarrera,Dorsal,Jockey)
VALUES ('CAB3','C6',99,'Romualdo');

4.INSERTA DOS CARRERAS CON LOS DATOS QUE CREAS NECESARIO.

INSERT INTO CARRERAS (CodCarrera)
VALUES ('CAR2');

INSERT INTO CARRERAS (CodCarrera)
VALUES ('CAR3');

5. QUITA EL CAMPO PROPIETARIO DE LA TABLA CABALLOS

ALTER TABLE CABALLOS
DROP column Propietario;

6.AÑADIR LAS SIQUIENTES RESTRICCIONES A LAS TABLAS

    • ALTER TABLE PARTICIPACIONES
	MODIFY Jockey CONSTRAINT INICIALES_MAYUS CHECK (initcap(Jockey) = Jockey);

    • 
      
    • ALTER TABLE CABALLOS
      MODIFY Nacionalidad CONSTRAINT NAC_PAISES CHECK(Nacionalidad IN('ESPAÑOLA','BRITÁNICA','ÁRABE'));



7. BORRA LAS CARRERAS EN LAS QUE NO HAY CABALLOS INSCRITOS

DELETE FROM CARRERAS
WHERE CodCarrera = (SELECT CodCarrera
FROM Participaciones
WHERE CodCaballo = NULL);
8. AÑADE UN CAMPO LLAMADO...

ALTER TABLE CLIENTES
add codigo VARCHAR2(10);


9.NOS HEMOS EQUIVOCADO...

(Tengo que modificar las FK que están asociadas a esta Primary Key)

UPDATE CARRERAS 
SET CodCarrera = 'C66' 
WHERE CodCarrera like 'C6';

10. AÑADE UN CAMPO LLAMADO PREMIO...

ALTER TABLE APUESTAS
add premios VARCHAR2(10);

11. BORRA TODO


DROP TABLE APUESTAS;
DROP TABLE CLIENTES;
DROP TABLE PARTICIPACIONES;
DROP TABLE CARRERAS;
DROP TABLE CABALLOS;